CREATE DATABASE VETERINARIA;
USE VETERINARIA;

--Inicio sesion user:admin pass:123

create table Users(
UserId int identity(1,1) primary key,
LoginName nvarchar(100) unique ,
password nvarchar(100) ,
Nombre nvarchar(100) ,
Apellido nvarchar(100) ,
Position nvarchar(100) ,
Email nvarchar(100),
)

CREATE TABLE CLIENTES(
ID_CLIENTE INT IDENTITY(1,1) PRIMARY KEY,
CEDULA VARCHAR(20),
NOMBRE VARCHAR(50),
APELLIDO VARCHAR(50),
TELEFONO varchar(50),
DIRECCION VARCHAR(100),
CORREO VARCHAR(100),
ID_MASCOTA INT
);
 
ALTER TABLE CLIENTES
ADD CONSTRAINT RELACION_A_MASCOTAS FOREIGN KEY (ID_MASCOTA) REFERENCES MASCOTAS (ID_MASCOTA);


CREATE TABLE MASCOTAS(
ID_MASCOTA INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE VARCHAR(50),
ID_RAZA INT,
PADECIMIENTO VARCHAR(50),
EDAD INT,
);

ALTER TABLE MASCOTAS
ADD CONSTRAINT RELACION_A_ESPECIE FOREIGN KEY (ID_RAZA) REFERENCES RAZAS (ID_RAZAS);


CREATE TABLE RAZAS(
ID_RAZAS INT IDENTITY(1,1) PRIMARY KEY,
RAZAS VARCHAR(50)
);

CREATE TABLE TRATAMIENTOS(
ID_TRATAMIENTO INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE_TRATAMIENTO VARCHAR(100),
PRECIO FLOAT
);

CREATE TABLE OPERACIONES(
ID_OPERACION INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE_OPERACION VARCHAR(100),
PRECIO FLOAT
);

CREATE TABLE PACIENTES_INTERNADOS(
ID_PACIENTE INT IDENTITY(1,1) PRIMARY KEY,
ID_MASCOTA INT,
ID_DUENO INT,
ID_TRATAMIENTO INT,
ID_OPERACION INT

CONSTRAINT RELACION_A_MASCOTAS_PI FOREIGN KEY (ID_MASCOTA) REFERENCES MASCOTAS (ID_MASCOTA),
CONSTRAINT RELACION_A_CLIENTES FOREIGN KEY (ID_DUENO) REFERENCES CLIENTES (ID_CLIENTE),
CONSTRAINT RELACION_A_TRATAMIENTOS FOREIGN KEY (ID_TRATAMIENTO) REFERENCES TRATAMIENTOS (ID_TRATAMIENTO),
CONSTRAINT RELACION_A_OPERACIONES FOREIGN KEY (ID_OPERACION) REFERENCES OPERACIONES (ID_OPERACION),
);

--8/13/20
--Por Hacer
--Modificar algo mas

CREATE TABLE PRODUCTOS(
ID_PRODUCTO INT IDENTITY(1,1) PRIMARY KEY,
ID_CATEGORIA INT,
NOMBRE_PRODUCTO VARCHAR(100),
DESCRIPCCION  VARCHAR(100),
CANTIDAD INT,
PRECIO FLOAT

CONSTRAINT RELACION_A_CATEGORIAS FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS (ID_CATEGORIA),
);

CREATE TABLE CATEGORIAS(
ID_CATEGORIA INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE_CATEGORIA VARCHAR(100),
);

CREATE TABLE FACTURA(
ID_FACTURA INT IDENTITY(1,1) PRIMARY KEY,
ID_CLIENTE INT,
ID_PRODUCTO INT,
ID_PACIENTES INT,

CONSTRAINT RELACION_A_PACIENTES FOREIGN KEY (ID_PACIENTES) REFERENCES PACIENTES_INTERNADOS (ID_PACIENTE),
);

--Inserts
insert into Users 
values
('admin',
'123',
'Jose',
'Padilla',
'Doctor',
'j@gmail.com')

insert into RAZAS 
values
('PERRO SIN RAZA/PERRO MESTIZO'),
('PASTOR ALEMÁN'),
('HUSKY SIBERIANO'),
('SAN BERNARDO'),
('AKITA INU'),
('LABRADOR RETRIEVER'),
('GOLDEN RETRIEVER'),
('SAMOYEDO'),
('BRACO DE WEIMAR'),
('MALAMUTE DE ALASKA'),
('ROTTWEILER'),
('SCHNAUZER'),
('BÓXER'),
('BORDER COLLIE')

insert into TRATAMIENTOS
values
('NINGUNO',0),
('Effitix pipetas antiparasitarias',40000),
('Aceite Grizzly de Salmón',11000),
('Four Paws Brewers Yeast con ajo',8000),
('Tabletas para perros y gatos',6000),
('Potty Mouth',23000),
('Crema Paw Guard',13000),
('Ear Wash 4 Oz', 13000),
('Ear Powder 24 Gramos',12000),
('Hemostatico Gel 1.16 Oz', 12000),
('Dosificador Para Pastillas', 4000),
('Tratamiento para impedir la Coprofagia',13000);

insert into OPERACIONES
values
('NINGUNO',0),
('Cirugía oncológica',2000000),
('Operación de la vista',5000000),
('Cirugía digestiva',10000000),
('Cirugía traumatológica',1000000),
('Operación de hernias',5000000),
('Cirugía del aparato urinario',1500000),
('Cirugía odontológica',500000);

insert into CATEGORIAS
values
('NINGUNO'),
('Alimentación'),
('Arenas'),
('Accesorios, Correas, Collares'),
('Bebederos y Comederos'),
('Camas'),
('Cepillos y Baño'),
('Rascadero y Postes'),
('Literas, Arena y Palas'),
('Juguetes'),
('Jaulas y Transportadoras'),
('Salud'),
('Medicamentos'),
('Ropa'),
('Antipulgas');

--Procedimiento almacenado
create proc listarPacientes
as
select ID_PACIENTE as ID,
CLIENTES.NOMBRE AS NombreCliente, 
CLIENTES.APELLIDO as ApellidoCliente,
MASCOTAS.NOMBRE as PacienteInternado, 
TRATAMIENTOS.NOMBRE_TRATAMIENTO as NombreTratamiento,
TRATAMIENTOS.PRECIO as PrecioTratamiento,
OPERACIONES.NOMBRE_OPERACION as NombreOperacion,
OPERACIONES.PRECIO as PrecioOperacion
from PACIENTES_INTERNADOS 
inner join MASCOTAS on PACIENTES_INTERNADOS.ID_MASCOTA = MASCOTAS.ID_MASCOTA
inner join CLIENTES on PACIENTES_INTERNADOS.ID_DUENO = CLIENTES.ID_CLIENTE
inner join TRATAMIENTOS on PACIENTES_INTERNADOS.ID_TRATAMIENTO = TRATAMIENTOS.ID_TRATAMIENTO
inner join OPERACIONES on PACIENTES_INTERNADOS.ID_OPERACION = OPERACIONES.ID_OPERACION;
go

create proc listarProductos
as
select
PRODUCTOS.ID_PRODUCTO,
CATEGORIAS.NOMBRE_CATEGORIA as CATEGORIA,
PRODUCTOS.NOMBRE_PRODUCTO AS NOMBRE,
PRODUCTOS.DESCRIPCCION,
PRODUCTOS.CANTIDAD,
PRODUCTOS.PRECIO
from
PRODUCTOS
INNER JOIN CATEGORIAS ON PRODUCTOS.ID_CATEGORIA = CATEGORIAS.ID_CATEGORIA
GO

create proc listarClientes
as
select
CLIENTES.ID_CLIENTE,
CLIENTES.CEDULA,
CLIENTES.NOMBRE,
CLIENTES.APELLIDO,
CLIENTES.TELEFONO,
CLIENTES.DIRECCION,
CLIENTES.CORREO,
MASCOTAS.NOMBRE as MASCOTA
from CLIENTES
inner join MASCOTAS on CLIENTES.ID_MASCOTA = MASCOTAS.ID_MASCOTA
go